### ISSUE TITLE
Tasmoadmin 1.8.0 not running after update (Docker on Raspberry Pi 3)

### ISSUE THREAD

**Issue by helmar74** [TasmoAdmin/TasmoAdmin#488]
Hi everyone,

I'm running tasmoadmin as a docker installation on my raspberry pi 3.
The Raspi is up to date.
Today I tried to install tasmoadmin 1.8.0, while following the instruction for Raspi Docker installation here:
https://github.com/TasmoAdmin/TasmoAdmin/wiki/Guide-for-TasmoAdmin-on-Docker

Finally it get's installed, but I can' connect to Webinterface.
```
pi@homesrv7:/app/Docker $ sudo docker ps
CONTAINER ID        IMAGE                                  COMMAND             CREATED             STATUS              PORTS                           NAMES
5b2ea67b7d0f        ghcr.io/tasmoadmin/tasmoadmin:latest   "/init"             7 seconds ago       Up 5 seconds        443/tcp, 0.0.0.0:5555->80/tcp   TasmoAdmin
51c2a03a954f        raymondmm/tasmoadmin                   "/init"             15 minutes ago      Up 15 minutes       443/tcp, 0.0.0.0:5556->80/tcp   TasmoAdmin17
beb97ebb066f        portainer/portainer                    "/portainer"        43 minutes ago      Up 3 minutes        0.0.0.0:9000->9000/tcp          Portainer
pi@homesrv7:/app/Docker $
```

Here same informations of  my docker environment:
```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 3
  Paused: 0
  Stopped: 2
 Images: 9
 Server Version: 19.03.15
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.66-v7+
 Operating System: Raspbian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 926.1MiB
 Name: homesrv7
 ID: WZND:7TMH:UOR4:SGNU:BWIQ:4LUG:MZH5:XCOV:MNWW:XY6F:V6GK:UXJ2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

The "old" version 1.7 of tasmoadmin is working without an issue  on port 5556. But if I try to connect to port 5555 (new version 1.8.0) the webinterface isn't loaded....

After waiting a long time I get this error in browser:
<img width="223" alt="image" src="https://user-images.githubusercontent.com/25499089/161948173-22918235-8706-412e-afaa-42e6efbf207d.png">

Also the load is really high on this machine

Any idea, what I can try?

**Comment by helmar74** [comment]
I also tried a completly new installation on a raspberry pi 4 with the installation guide:
https://github.com/TasmoAdmin/TasmoAdmin/wiki/Guide-for-TasmoAdmin-on-Docker
```
pi@ws400:/var/log $ sudo docker ps
CONTAINER ID   IMAGE                                                 COMMAND   CREATED          STATUS          PORTS                                            NAMES
015176ec97f9   ghcr.io/tasmoadmin/tasmoadmin:v1.8.0-alpine-arm32v6   "/init"   33 seconds ago   Up 31 seconds   443/tcp, 0.0.0.0:5555->80/tcp, ::pi@ws400:/vpi@ws400:/var/log $
```

The image starts, but I can't connect to the webinterface on port 5555

**Comment by helmar74** [comment]
The info.php in the container is working, when I call http://192.168.xxx.xxx:5555/info.php

**Comment by inverse** [comment]
We did bump the QMU version from `v2.12.0` to `v6.1.0-8` would that cause such an issue? 

See: https://github.com/TasmoAdmin/TasmoAdmin/pull/471

**Comment by helmar74** [comment]
Hi, thanks for you reply.
I restarted the container and logged in.
Here's the output of /var/log/nginx/error.log while trying to connect to TasmoAdmin with Chrome browser:
```
bash-5.1# cat /var/log/nginx/error.log
2071/05/03 07:39:04 [error] 2739#2739: *1 open() "/var/www/tasmoadmin/favicon.ico" failed (2: No such file or directory), client: 192.168.1.31, server: tasmoadmin.local, request: "GET /favicon.ico HTTP/1.1", host: "192.168.1.229:5555", referrer: "http://192.168.1.229:5555/info.php"
```

**Comment by inverse** [comment]
That doesn't look so bad - just that we shoud probably include a favicon :)

**Comment by inverse** [comment]
Just span up an arm instance on AWS and unable to reproduce the issue :(

Spun up the container with:

```bash
docker run -it -p 8000:80 ghcr.io/tasmoadmin/tasmoadmin:latest
```

and connected to it locally with:

```bash
ssh -N -i cert.pem <user>@<public-ip> -L 8001:localhost:8000
```

and accessed at http://localhost:8001

**Comment by helmar74** [comment]
I let the container run until the 502 appears in the browser window.
Here's the log output after 502 appears:
```
bash-5.1# tail -f /var/log/nginx/error.log
2071/05/03 07:39:04 [error] 2739#2739: *1 open() "/var/www/tasmoadmin/favicon.ico" failed (2: No such file or directory), client: 192.168.1.31, server: tasmoadmin.local, request: "GET /favicon.ico HTTP/1.1", host: "192.168.1.229:5555", referrer: "http://192.168.1.229:5555/info.php"
##############################################################################
2071/05/17 22:05:12 [error] 2738#2738: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.1.31, server: tasmoadmin.local, request: "GET /start HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "192.168.1.229:5555"
2071/05/17 22:05:12 [error] 2738#2738: *1 open() "/var/www/tasmoadmin/favicon.ico" failed (2: No such file or directory), client: 192.168.1.31, server: tasmoadmin.local, request: "GET /favicon.ico HTTP/1.1", host: "192.168.1.229:5555", referrer: "http://192.168.1.229:5555/start"
2071/05/17 22:05:12 [error] 2738#2738: *3 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.1.31, server: tasmoadmin.local, request: "GET /start HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "192.168.1.229:5555"

```

**Comment by helmar74** [comment]
Output docker top TasmoAdmin:
```
pi@ws400:~ $ sudo docker top TasmoAdmin
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                27986               27962               0                   10:37               ?                   00:00:00            s6-svscan -t0 /var/run/s6/services
root                28072               27986               0                   10:37               ?                   00:00:00            s6-supervise s6-fdholderd
root                30762               27986               0                   10:37               ?                   00:00:00            s6-supervise nginx
root                30763               27986               0                   10:37               ?                   00:00:00            s6-supervise php-fpm
root                30766               30762               0                   10:37               ?                   00:00:00            nginx: master process nginx -g daemon off;
root                30767               30763               0                   10:37               ?                   00:00:00            php-fpm: master process (/etc/php7/php-fpm.conf)
systemd+            30785               30766               0                   10:37               ?                   00:00:00            nginx: worker process
systemd+            30788               30767               0                   10:37               ?                   00:00:00            php-fpm: pool www
root                30810               27962               0                   10:37               pts/0               00:00:00            /bin/bash
systemd+            30886               30767               0                   10:53               ?                   00:00:00            php-fpm: pool www
systemd+            31019               30767               0                   11:08               ?                   00:00:00            php-fpm: pool www
```

**Comment by helmar74** [comment]
> ```shell
> ssh -N -i cert.pem <user>@<public-ip> -L 8001:localhost:8000
> ```

This doesn't work either:
```
pi@ws400:~ $ sudo docker run -it -p 8000:80 ghcr.io/tasmoadmin/tasmoadmin:latest
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying...
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-requirements.sh: executing...
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 12-patches.sh: executing...
[cont-init.d] 12-patches.sh: exited 0.
[cont-init.d] 13-persistent-data-nginx.sh: executing...
Data nginx directory not initialized, doing that now...
'/etc/nginx/nginx.conf' -> '/etc/nginx/nginx.conf.org'
'/etc/nginx/nginx.conf.org' -> '/data/nginx/nginx.conf.org'
'/data/nginx/nginx.conf.org' -> '/data/nginx/nginx.conf'
'/etc/nginx/nginx-ssl.conf' -> '/data/nginx/nginx-ssl.conf'
'/etc/nginx/certs/README.md' -> '/data/nginx/certs/README.md'
'/etc/nginx/certs/tasmoadmin.conf' -> '/data/nginx/certs/tasmoadmin.conf'
'/etc/nginx/certs/tasmoadmin.crt' -> '/data/nginx/certs/tasmoadmin.crt'
'/etc/nginx/certs/tasmoadmin.key' -> '/data/nginx/certs/tasmoadmin.key'
Symlinking /etc/nginx.conf to persistent storage location...
[cont-init.d] 13-persistent-data-nginx.sh: exited 0.
[cont-init.d] 14-nginx-ssl.sh: executing...
[cont-init.d] 14-nginx-ssl.sh: exited 0.
[cont-init.d] 15-docker-environment.sh: executing...
[cont-init.d] 15-docker-environment.sh: exited 0.
[cont-init.d] 16-persistent-data-tasmoadmin.sh: executing...
Data directory not initialized, doing that now...
'/var/www/tasmoadmin/data/firmwares' -> '/data/tasmoadmin/firmwares'
'/var/www/tasmoadmin/data/updates' -> '/data/tasmoadmin/updates'
Symlinking data/tasmoadmin directory to persistent storage location...
[cont-init.d] 16-persistent-data-tasmoadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16-Apr-2071 04:06:16] NOTICE: fpm is running, pid 2704
[16-Apr-2071 04:04:56] NOTICE: ready to handle connections
```

```
ssh -N -i cert.pem pi@192.168.1.229 -L 8001:localhost:8000
Warning: Identity file cert.pem not accessible: No such file or directory.
The authenticity of host '192.168.1.229 (192.168.1.229)' can't be established.
ECDSA key fingerprint is SHA256:J6IuaRDcBKrPlXBwPAJGZFKVCOh6xxeLaFodS8DlJ0U.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.1.229' (ECDSA) to the list of known hosts.
pi@192.168.1.229's password:

```

**Comment by helmar74** [comment]
For me it looks like, static html traffic is working, but the tasmoadmin php application is failing.
When I restart the container and I type the following URL in Browser the TasmoAdmin Logo is shown:
<img width="679" alt="image" src="https://user-images.githubusercontent.com/25499089/163671171-359685ca-9036-47e6-bbe1-521e6d6ce1b2.png">


When trying 
```
http://192.168.1.229:5555/login.php
```
It takes a long time then the 502 is shown

**Comment by helmar74** [comment]
Just for my understanding

> I let the container run until the 502 appears in the browser window. Here's the log output after 502 appears:
> 
> ```
> bash-5.1# tail -f /var/log/nginx/error.log
> 2071/05/03 07:39:04 [error] 2739#2739: *1 open() "/var/www/tasmoadmin/favicon.ico" failed (2: No such file or directory), client: 192.168.1.31, server: tasmoadmin.local, request: "GET /favicon.ico HTTP/1.1", host: "192.168.1.229:5555", referrer: "http://192.168.1.229:5555/info.php"
> ##############################################################################
> 2071/05/17 22:05:12 [error] 2738#2738: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.1.31, server: tasmoadmin.local, request: "GET /start HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "192.168.1.229:5555"
> 2071/05/17 22:05:12 [error] 2738#2738: *1 open() "/var/www/tasmoadmin/favicon.ico" failed (2: No such file or directory), client: 192.168.1.31, server: tasmoadmin.local, request: "GET /favicon.ico HTTP/1.1", host: "192.168.1.229:5555", referrer: "http://192.168.1.229:5555/start"
> 2071/05/17 22:05:12 [error] 2738#2738: *3 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.1.31, server: tasmoadmin.local, request: "GET /start HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "192.168.1.229:5555"
> ```

Just for my understand.
In the logs the date 2071/05/17 22:05:12 is shown... Could the problem be related due to a certificate issue, as the time isn't correct?

**Comment by inverse** [comment]
Looks like something is up with `php-fpm` what's in `cat /var/log/php7/error.log`?

**Comment by helmar74** [comment]
On my working Tasmoadmin 1.7.0 environment the  date an times are correct:
```
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS                           NAMES
51c2a03a954f        raymondmm/tasmoadmin   "/init"             10 days ago         Up 10 days          443/tcp, 0.0.0.0:5556->80/tcp   TasmoAdmin17
pi@homesrv7:~ $ sudo docker exec -it TasmoAdmin17 /bin/bash
bash-5.0# date
Sat Apr 16 10:31:46 UTC 2022
bash-5.0# exit
```

**Comment by helmar74** [comment]
> cat /var/log/php7/error.log

```
pi@ws400:~ $ sudo docker exec -it TasmoAdmin /bin/bash
bash-5.1# cat /var/log/php7/error.log
[03-Jul-2071 17:24:24] NOTICE: fpm is running, pid 2696
[03-Jul-2071 17:23:04] NOTICE: ready to handle connections
[03-Jul-2071 17:21:28] NOTICE: Terminating ...
[03-Jul-2071 17:18:24] NOTICE: exiting, bye-bye!
[24-Jun-2071 19:30:16] NOTICE: fpm is running, pid 2726
[24-Jun-2071 19:28:56] NOTICE: ready to handle connections
bash-5.1#
```

**Comment by helmar74** [comment]
Does anyone know how to sync date and time in docker container?

**Comment by inverse** [comment]
It sounds similar to https://konubinix.eu/braindump/posts/docker_buildx_cross_compiling_python_to_armhf_fatal_python_error_pyinit_main_can_t_initialize_time/

I pushed the images from my laptop due to issues on CI before but in the next version that should be resolved.

You could try building the image on your PI directly. There is currently an issue with translations on the master branch which I will try and fix when I have time.

but if you checkout the repo on your pi and run `make` it should build all 3 images.

and give you three images for the various arch's

```
ghcr.io/tasmoadmin/tasmoadmin:build-alpine-arm32v6
ghcr.io/tasmoadmin/tasmoadmin:build-alpine-amd64 
ghcr.io/tasmoadmin/tasmoadmin:build-alpine-arm64v8
```

**Comment by helmar74** [comment]
Hi thanks for the info.
Unfourtnately I'm not aware how to build the docker image by my own, so 
I think I'll wait for the new version and give it a try...

**Comment by inverse** [comment]
> Unfourtnately I'm not aware how to build the docker image by my own, so I think I'll wait for the new version and give it a try...

Okays - it's not that difficult if you've got your pi with docker aready setup. It should just be a case of cloning this repo to your pi and running `make` in that directory :)

**Comment by helmar74** [comment]
do you have the commands for cloning and running make? ;-)

**Comment by inverse** [comment]
Not seen that error when building things :/ The warning before I did due to building multi-arch but not

```
standard_init_linux.go:228: exec user process caused: exec format error
```

perhaps it can only be built on x86 - We really need to streamline this multiarch setup with buildx or something less custom.

**Comment by helmar74** [comment]
In the documentation docker is named as "recommended way"_
![image](https://user-images.githubusercontent.com/25499089/164167179-e42401c8-9f80-4a0c-a6a0-7bed50b734aa.png)


![image](https://user-images.githubusercontent.com/25499089/164167245-1cad5904-64fb-47e6-8e58-12bf7f9e0dda.png)


Maybe there should be a hint, that tasmoadmin 1.8.0 isn't working with docker on raspberry pi's?

**Comment by inverse** [comment]
@RaymondMouthaan did you have these issues when building the multi-arch setup?

**Comment by inverse** [comment]
@helmar74 I just managed to successfully setup the beta build for the repo

See: https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.0.0-beta1

Would you be able to try running this image? `ghcr.io/tasmoadmin/tasmoadmin:beta`?

**Comment by helmar74** [comment]
> ghcr.io/tasmoadmin/tasmoadmin:beta

I tried the beta version still no response in browser window :

<img width="184" alt="image" src="https://user-images.githubusercontent.com/25499089/164684188-a4cb6ea3-a2b9-42f3-84c6-2c730405e43e.png">

```
pi@ws400:~ $ sudo docker ps
CONTAINER ID   IMAGE                                COMMAND   CREATED          STATUS          PORTS                                            NAMES
00ebda3318c4   ghcr.io/tasmoadmin/tasmoadmin:beta   "/init"   34 seconds ago   Up 33 seconds   443/tcp, 0.0.0.0:5555->80/tcp, :::5555->80/tcp   TasmoAdmin
```

**Comment by imkebe** [comment]
Same here. Beta version hasn't changed anything.

**Comment by inverse** [comment]
Interesting I just setup a Pi3 B+ and installed dietpi  and ran `docker run -it -p 8000:80 ghcr.io/tasmoadmin/tasmoadmin:beta` on it and can view things just fine.

![image](https://user-images.githubusercontent.com/713525/164784198-9da1e361-d445-42f0-ba30-fd6d665c98ba.png)

**Comment by helmar74** [comment]
> docker run -it -p 8000:80 ghcr.io/tasmoadmin/tasmoadmin:beta

Just tried it, doesn't work for me:
```
pi@ws400:~ $ sudo docker run -it -p 8000:80 ghcr.io/tasmoadmin/tasmoadmin:beta
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying...
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-requirements.sh: executing...
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 12-patches.sh: executing...
[cont-init.d] 12-patches.sh: exited 0.
[cont-init.d] 13-persistent-data-nginx.sh: executing...
Data nginx directory not initialized, doing that now...
'/etc/nginx/nginx.conf' -> '/etc/nginx/nginx.conf.org'
'/etc/nginx/nginx.conf.org' -> '/data/nginx/nginx.conf.org'
'/data/nginx/nginx.conf.org' -> '/data/nginx/nginx.conf'
'/etc/nginx/nginx-ssl.conf' -> '/data/nginx/nginx-ssl.conf'
'/etc/nginx/certs/README.md' -> '/data/nginx/certs/README.md'
'/etc/nginx/certs/tasmoadmin.conf' -> '/data/nginx/certs/tasmoadmin.conf'
'/etc/nginx/certs/tasmoadmin.crt' -> '/data/nginx/certs/tasmoadmin.crt'
'/etc/nginx/certs/tasmoadmin.key' -> '/data/nginx/certs/tasmoadmin.key'
Symlinking /etc/nginx.conf to persistent storage location...
[cont-init.d] 13-persistent-data-nginx.sh: exited 0.
[cont-init.d] 14-nginx-ssl.sh: executing...
[cont-init.d] 14-nginx-ssl.sh: exited 0.
[cont-init.d] 15-docker-environment.sh: executing...
Docker env does not exist, doing that now...
[cont-init.d] 15-docker-environment.sh: exited 0.
[cont-init.d] 16-persistent-data-tasmoadmin.sh: executing...
Data directory not initialized, doing that now...
'/var/www/tasmoadmin/data/firmwares' -> '/data/tasmoadmin/firmwares'
'/var/www/tasmoadmin/data/updates' -> '/data/tasmoadmin/updates'
Symlinking /data/tasmoadmin directory to persistent storage location...
[cont-init.d] 16-persistent-data-tasmoadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[03-May-2071 14:48:24] NOTICE: fpm is running, pid 374
[03-May-2071 14:47:04] NOTICE: ready to handle connections

```

**Comment by inverse** [comment]
@imkebe what hardware and what's the output of `docker info`?

**Comment by inverse** [comment]
@helmar74 main differences I see are docker version (19 vs 20), kernel version (4.19 vs 5.15)

**Comment by imkebe** [comment]
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)

Server:
 Containers: 6
  Running: 5
  Paused: 0
  Stopped: 1
 Images: 11
 Server Version: 20.10.14
 Storage Driver: btrfs
  Build Version: Btrfs v4.20.1 
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.15.25-sunxi
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 1.967GiB
 Name: orangepiplus
 ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by imkebe** [comment]
ngnix and php error log files doesn't reveal anything helpfull

**Comment by imkebe** [comment]
I found the [problem](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12091). It's related to alpine base image.
Internally if you log into container it can't resolver any address. Try to ping or wget localhost etc.
I've got similar 
```
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: clock_gettime(MONOTONIC) failed
```

At the end of the issue report there is a nasty workaround  - add `--security-opt seccomp=unconfined` to container definition command.

Maybe upgrading alpine version to the lastest would help? That bug is related to 3.13 however i can see that tasmoadmin is based on 3.15

**Comment by helmar74** [comment]
> I found the [problem](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12091). It's related to alpine base image. Internally if you log into container it can't resolver any address. Try to ping or wget localhost etc. I've got similar
> 
> ```
> PING 8.8.8.8 (8.8.8.8): 56 data bytes
> ping: clock_gettime(MONOTONIC) failed
> ```
> 
> At the end of the issue report there is a nasty workaround - add `--security-opt seccomp=unconfined` to container definition command. I can confirm it is working for me now.
> 
> Maybe upgrading alpine version to the lastest would help? That bug is related to 3.13 however i can see that tasmoadmin is based on 3.15

I can confirm, that the options above fix the issue.
Here's my output:
```
pi@ws400:~ $ sudo docker run -it -p 5555:80 --security-opt seccomp=unconfined ghcr.io/tasmoadmin/tasmoadmin:latest
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying...
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-requirements.sh: executing...
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 12-patches.sh: executing...
[cont-init.d] 12-patches.sh: exited 0.
[cont-init.d] 13-persistent-data-nginx.sh: executing...
Data nginx directory not initialized, doing that now...
'/etc/nginx/nginx.conf' -> '/etc/nginx/nginx.conf.org'
'/etc/nginx/nginx.conf.org' -> '/data/nginx/nginx.conf.org'
'/data/nginx/nginx.conf.org' -> '/data/nginx/nginx.conf'
'/etc/nginx/nginx-ssl.conf' -> '/data/nginx/nginx-ssl.conf'
'/etc/nginx/certs/README.md' -> '/data/nginx/certs/README.md'
'/etc/nginx/certs/tasmoadmin.conf' -> '/data/nginx/certs/tasmoadmin.conf'
'/etc/nginx/certs/tasmoadmin.crt' -> '/data/nginx/certs/tasmoadmin.crt'
'/etc/nginx/certs/tasmoadmin.key' -> '/data/nginx/certs/tasmoadmin.key'
Symlinking /etc/nginx.conf to persistent storage location...
[cont-init.d] 13-persistent-data-nginx.sh: exited 0.
[cont-init.d] 14-nginx-ssl.sh: executing...
[cont-init.d] 14-nginx-ssl.sh: exited 0.
[cont-init.d] 15-docker-environment.sh: executing...
[cont-init.d] 15-docker-environment.sh: exited 0.
[cont-init.d] 16-persistent-data-tasmoadmin.sh: executing...
Data directory not initialized, doing that now...
'/var/www/tasmoadmin/data/firmwares' -> '/data/tasmoadmin/firmwares'
'/var/www/tasmoadmin/data/updates' -> '/data/tasmoadmin/updates'
Symlinking data/tasmoadmin directory to persistent storage location...
[cont-init.d] 16-persistent-data-tasmoadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23-Apr-2022 12:29:29] NOTICE: fpm is running, pid 2705
[23-Apr-2022 12:29:29] NOTICE: ready to handle connections
```

**Comment by helmar74** [comment]
I'll wait a few days, maybe it is fixed in the alpine image?

**Comment by inverse** [comment]
Would moving the alpine version back down to 3.13 resolve this? Unfortunately I'm unable to reproduce on a pi3 running dietpi.

**Comment by imkebe** [comment]
@inverse I don't think so. It was reported for 3.13 and looks like it's still valid for 3.15 :(

**Comment by inverse** [comment]
What's strange is that 1.7 worked which was based on 3.13 :/

**Comment by inverse** [comment]
@helmar74 I added `dev` tagged images that are build from the master branch.

I just merged this change downgrading Alpine to 3.13 - https://github.com/TasmoAdmin/TasmoAdmin/pull/511

You should be able to run `ghcr.io/tasmoadmin/tasmoadmin:dev` this image shortly with that change applied - let me know if this did anything?

**Comment by helmar74** [comment]
> @helmar74 I added `dev` tagged images that are build from the master branch.
> 
> I just merged this change downgrading Alpine to 3.13 - #511
> 
> You should be able to run `ghcr.io/tasmoadmin/tasmoadmin:dev` this image shortly with that change applied - let me know if this did anything?

No unfourtnately this didn' changed anything. I still can't connect to Tasmoadmin Login Page.
Here's the output:
```
pi@ws400:~ $ sudo docker run -it -p 5555:80  ghcr.io/tasmoadmin/tasmoadmin:dev
Unable to find image 'ghcr.io/tasmoadmin/tasmoadmin:dev' locally
dev: Pulling from tasmoadmin/tasmoadmin
83a39d5693a8: Pull complete
a70fea150a7a: Pull complete
8fb80d5bfa15: Pull complete
bd37ca68b07a: Pull complete
fa35324ddb50: Pull complete
ef57f0af7cd3: Pull complete
1a4f2b7f2a73: Pull complete
16e78c379bd3: Pull complete
Digest: sha256:c5aa855fa6ad6af9b1a99ad592a150934f95b4d4f0abffd8e8ed832f08297b51
Status: Downloaded newer image for ghcr.io/tasmoadmin/tasmoadmin:dev
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying...
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-requirements.sh: executing...
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 12-patches.sh: executing...
[cont-init.d] 12-patches.sh: exited 0.
[cont-init.d] 13-persistent-data-nginx.sh: executing...
Data nginx directory not initialized, doing that now...
'/etc/nginx/nginx.conf' -> '/etc/nginx/nginx.conf.org'
'/etc/nginx/nginx.conf.org' -> '/data/nginx/nginx.conf.org'
'/data/nginx/nginx.conf.org' -> '/data/nginx/nginx.conf'
'/etc/nginx/nginx-ssl.conf' -> '/data/nginx/nginx-ssl.conf'
'/etc/nginx/certs/README.md' -> '/data/nginx/certs/README.md'
'/etc/nginx/certs/tasmoadmin.conf' -> '/data/nginx/certs/tasmoadmin.conf'
'/etc/nginx/certs/tasmoadmin.crt' -> '/data/nginx/certs/tasmoadmin.crt'
'/etc/nginx/certs/tasmoadmin.key' -> '/data/nginx/certs/tasmoadmin.key'
Symlinking /etc/nginx.conf to persistent storage location...
[cont-init.d] 13-persistent-data-nginx.sh: exited 0.
[cont-init.d] 14-nginx-ssl.sh: executing...
[cont-init.d] 14-nginx-ssl.sh: exited 0.
[cont-init.d] 15-docker-environment.sh: executing...
Docker env does not exist, doing that now...
[cont-init.d] 15-docker-environment.sh: exited 0.
[cont-init.d] 16-persistent-data-tasmoadmin.sh: executing...
Data directory not initialized, doing that now...
'/var/www/tasmoadmin/data/firmwares' -> '/data/tasmoadmin/firmwares'
'/var/www/tasmoadmin/data/updates' -> '/data/tasmoadmin/updates'
Symlinking /data/tasmoadmin directory to persistent storage location...
[cont-init.d] 16-persistent-data-tasmoadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[07-Jun-2071 03:06:24] NOTICE: fpm is running, pid 376
[07-Jun-2071 03:05:12] NOTICE: ready to handle connections
```

**Comment by helmar74** [comment]
If I run with options 
```
--security-opt seccomp=unconfined
```
it works.
Here's the output of this:
```
sudo docker run -it -p 5555:80 --security-opt seccomp=unconfined ghcr.io/tasmoadmin/tasmoadmin:dev
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying...
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-requirements.sh: executing...
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 12-patches.sh: executing...
[cont-init.d] 12-patches.sh: exited 0.
[cont-init.d] 13-persistent-data-nginx.sh: executing...
Data nginx directory not initialized, doing that now...
'/etc/nginx/nginx.conf' -> '/etc/nginx/nginx.conf.org'
'/etc/nginx/nginx.conf.org' -> '/data/nginx/nginx.conf.org'
'/data/nginx/nginx.conf.org' -> '/data/nginx/nginx.conf'
'/etc/nginx/nginx-ssl.conf' -> '/data/nginx/nginx-ssl.conf'
'/etc/nginx/certs/README.md' -> '/data/nginx/certs/README.md'
'/etc/nginx/certs/tasmoadmin.conf' -> '/data/nginx/certs/tasmoadmin.conf'
'/etc/nginx/certs/tasmoadmin.crt' -> '/data/nginx/certs/tasmoadmin.crt'
'/etc/nginx/certs/tasmoadmin.key' -> '/data/nginx/certs/tasmoadmin.key'
Symlinking /etc/nginx.conf to persistent storage location...
[cont-init.d] 13-persistent-data-nginx.sh: exited 0.
[cont-init.d] 14-nginx-ssl.sh: executing...
[cont-init.d] 14-nginx-ssl.sh: exited 0.
[cont-init.d] 15-docker-environment.sh: executing...
Docker env does not exist, doing that now...
[cont-init.d] 15-docker-environment.sh: exited 0.
[cont-init.d] 16-persistent-data-tasmoadmin.sh: executing...
Data directory not initialized, doing that now...
'/var/www/tasmoadmin/data/firmwares' -> '/data/tasmoadmin/firmwares'
'/var/www/tasmoadmin/data/updates' -> '/data/tasmoadmin/updates'
Symlinking /data/tasmoadmin directory to persistent storage location...
[cont-init.d] 16-persistent-data-tasmoadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[24-Apr-2022 06:20:39] NOTICE: fpm is running, pid 384
[24-Apr-2022 06:20:39] NOTICE: ready to handle connections
```

**Comment by inverse** [comment]
@helmar74 I also downgraded QEMU in https://github.com/TasmoAdmin/TasmoAdmin/pull/515 which is the same as the version in 1.7. 

If this doesn't work I'm not sure what else we can do aside the `--security-opt seccomp=unconfined` which feels not so great.

**Comment by helmar74** [comment]
> @helmar74 + @imkebe I also downgraded QEMU in #515 which is the same as the version in 1.7.
> 
> If this doesn't work I'm not sure what else we can do aside the `--security-opt seccomp=unconfined` which feels like a hack.

I just tried latest and dev, both doesn'T work for me...

**Comment by inverse** [comment]
@helmar74 that's a shame Nothing else really changed on that side aside `3.13` is not tied to the same patch version as `1.7`

**Comment by helmar74** [comment]
Maybe it should be mentioned in the documentation, that tasmoadmin 1.8.0 isn't running on Raspberry Pi's anymore?

**Comment by inverse** [comment]
@helmar74 It does work through.

See: https://github.com/TasmoAdmin/TasmoAdmin/issues/488#issuecomment-1106811069

**Comment by helmar74** [comment]
In the meantime I tried it on a Raspi 3B+ and on a Raspi 400, both systems were up to date and I used the description for installation. 
On both systems the installation failed with the same error...
[imkebe](https://github.com/imkebe) also has the same issue... So probably something is wrong here?

**Comment by inverse** [comment]
We can leave this thread open to see how widespread the issue is  and to better understand the conditions it happens in.

**Comment by helmar74** [comment]
Again had a look on the issue.
I pulled the DEV Image newly. Now Dev is working:
```
sudo docker pull ghcr.io/tasmoadmin/tasmoadmin:latest
latest: Pulling from tasmoadmin/tasmoadmin
Digest: sha256:13ca5879c512419915f8965122a7ccf70c6959b78cba189932145ce5e65f01a1
Status: Image is up to date for ghcr.io/tasmoadmin/tasmoadmin:latest
ghcr.io/tasmoadmin/tasmoadmin:latest
pi@ws400:~ $ sudo docker pull ghcr.io/tasmoadmin/tasmoadmin:dev
dev: Pulling from tasmoadmin/tasmoadmin
c319b1fc4ed7: Already exists
7c245d541057: Pull complete
2a8f0ca4072e: Pull complete
beb04400bd44: Pull complete
7c0c4e617cc8: Pull complete
bef0c9c6ee6e: Pull complete
c6c37331d249: Pull complete
42a5fa43daa5: Pull complete
Digest: sha256:de7687f03eac3de0d51259471d824c5d02b018b331991afb628013095a5a727b
Status: Downloaded newer image for ghcr.io/tasmoadmin/tasmoadmin:dev
ghcr.io/tasmoadmin/tasmoadmin:dev
pi@ws400:~ $ sudo docker run -it -p 5555:80 ghcr.io/tasmoadmin/tasmoadmin:dev
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying...
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-requirements.sh: executing...
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 12-patches.sh: executing...
[cont-init.d] 12-patches.sh: exited 0.
[cont-init.d] 13-persistent-data-nginx.sh: executing...
Data nginx directory not initialized, doing that now...
'/etc/nginx/nginx.conf' -> '/etc/nginx/nginx.conf.org'
'/etc/nginx/nginx.conf.org' -> '/data/nginx/nginx.conf.org'
'/data/nginx/nginx.conf.org' -> '/data/nginx/nginx.conf'
'/etc/nginx/nginx-ssl.conf' -> '/data/nginx/nginx-ssl.conf'
'/etc/nginx/certs/README.md' -> '/data/nginx/certs/README.md'
'/etc/nginx/certs/tasmoadmin.conf' -> '/data/nginx/certs/tasmoadmin.conf'
'/etc/nginx/certs/tasmoadmin.crt' -> '/data/nginx/certs/tasmoadmin.crt'
'/etc/nginx/certs/tasmoadmin.key' -> '/data/nginx/certs/tasmoadmin.key'
Symlinking /etc/nginx.conf to persistent storage location...
[cont-init.d] 13-persistent-data-nginx.sh: exited 0.
[cont-init.d] 14-nginx-ssl.sh: executing...
[cont-init.d] 14-nginx-ssl.sh: exited 0.
[cont-init.d] 15-docker-environment.sh: executing...
Docker env does not exist, doing that now...
[cont-init.d] 15-docker-environment.sh: exited 0.
[cont-init.d] 16-persistent-data-tasmoadmin.sh: executing...
Data directory not initialized, doing that now...
'/var/www/tasmoadmin/data/firmwares' -> '/data/tasmoadmin/firmwares'
'/var/www/tasmoadmin/data/updates' -> '/data/tasmoadmin/updates'
Symlinking /data/tasmoadmin directory to persistent storage location...
[cont-init.d] 16-persistent-data-tasmoadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[03-Jul-2071 18:32:24] NOTICE: fpm is running, pid 374
[03-Jul-2071 18:31:04] NOTICE: ready to handle connections

```

**Comment by inverse** [comment]
Thanks for retesting it - yeah `latest` is still the `1.8.0` tagged version which is a lot further behind.

Hopefully will be able to rollout the `2.0.0` release as it's already been picked up by the Home Assistant community and some bugs ironed out from that.

**Comment by helmar74** [comment]
Hi, I found a solution!
Had to update libseccomp2 as this package isn't compatible with older raspberryPiOS versions.
The Alpine Image (> Version 3.12) isn't working correctly, if the library isn't updated.
So the container don't get any network connectivity in the end

Mentionend here:
[https://docs.linuxserver.io/faq#libseccomp](https://docs.linuxserver.io/faq#libseccomp)


Has done this:
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
echo "deb http://deb.debian.org/debian buster-backports main" | sudo tee -a /etc/apt/sources.list.d/buster-backports.list
sudo apt update
sudo apt install -t buster-backports libseccomp2
```

Then restarted container, everything is fine...
